### ISSUE TITLE
EncryptionUtils.cs

### ISSUE THREAD

**Issue by TheDestinyGroup** [alecgn/crypthash-net#1]
Alessandro,

I just came across your project and it looks like a great library.

Whilst reviewing the code I noticed a couple things that look like possible bugs in EncryptionUtils.cs.

Firstly throughout EncryptionUtils.cs you seem to be referencing nameof(authKey) instead of nameof(dataBytes) in the ArgumentException calls for DataBaytes.

Secondly in ComputeHMACSHA512HashFromDataBytes you seem to have the messages in the ArgumentException calls for validating the authKey and DataBaytes reversed.

Thirdly in TagsMatch there is a typo with the word equal.

Les

PS: Can you explain the reasoning behind using the variable name tag instead of hash in some of the functions within EncryptionUtils.cs. To me variable name hash would be more appropriate and less likely to cause confusion with the use of the tag variable in the actual encryption functions.

**Comment by alecgn** [comment]
Hi.

Thanks for you report and feedback!
I noticed the inconsistencies and errors reported, and I fixed by https://github.com/alecgn/crypthash-net/commit/332c93596f5d305d8e1751403101f058e14c8645.
About the variable names "tag" and "hash", you're right, the concepts are really diferent one from another, so I fixed that too.

**Comment by TheDestinyGroup** [comment]
Alessandro,

Thanks for listening to my feedback and taking it on board.

Les
