### ISSUE TITLE
Mono Runtime cannot support.

### ISSUE THREAD

**Issue by dydhub** [alecgn/crypthash-net#20]

**Comment by alecgn** [comment]
Hi @dydhub, could you be more specific please? What features didn't work on Mono?
When running on Mono, be aware of the following limmitations and compatibility issues, as described in https://www.mono-project.com/docs/about-mono/compatibility .
In short, you project must target .NET Framework (aka ".NET Full") 4.7 and below, preferably .NET 4.7 because it's the higher compatible version. Everything in .NET 4.7 except WPF, WWF, and with limited WCF and limited ASP.NET async stack. System.Web and WCF has little issues either, and are candidates for ‘almost immediate’ porting from the .NET reference source back to Mono, so support coverage may improve in future.

**Comment by dydhub** [comment]
I just saw this:
[https://github.com/mono/mono/issues/19285](https://github.com/mono/mono/issues/19285)
I want to use Aesgcm to develop in C# on the mobile platform, Do you have any ideas?

**Comment by alecgn** [comment]
.NET Framework 4.7, wich is the highest version supported by Mono, according to the compatibility link sent above, has only partial .NET Standard 2.0 support; AES GCM was introduced in version 2.1 of .NET Standard, I myself requested for that in [this issue](https://github.com/dotnet/standard/issues/1295).
This way, I belive Mono have no support for AES GCM, but in [this link](https://github.com/dotnet/standard/blob/master/docs/versions.md) .NET Standard Dev Team refers that Mono 6.4, Xamarin.iOS 12.16, Xamarin.Mac 5.16 and Xamarin.Android 10.0 does have .NET Standard 2.1 support.
That said, I believe this current issue is more related to Mono/Xamarin versions instead of CryptHash.Net, do you agree?

**Comment by alecgn** [comment]
In the source code I handle the availability of AES GCM using a compiler/preprocessor directive: 

```
#if NETSTANDARD2_1

... code for AES GCM ...

#endif
```

**Comment by alecgn** [comment]
Closing this issue, since the reported situation is outside the scope of this project, it is a problem directly related to Mono.
